### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by Happy-Ferret** [mk-fg/notification-thing#3]
As a newbie to gtk3, I'm wondering whether there is any straightforward way to implement rounded corners for the notifications. Preferably through css. 

As it stands, if I set the border radius of ```#notification #frame``` to 15px, I end up with something similar to this (sorry for not providing an actual screenshot out of notification-thing, I'm currently not at my development machine).

![25](https://cloud.githubusercontent.com/assets/1962554/10495369/d0d3ea4c-72bb-11e5-9ea3-f372987dbb5b.png)

Expected behaviour: Smooth round borders with no square element obstructing the view.

PS: I've tested this under both, Ubuntu's Unity desktop and fvwm + compton. The issue is present under both systems. My target distro uses fvwm + compton, so the fix should be compatible with this setup.

**Comment by mk-fg** [comment]
Given that gtk originated in X11 environment, I can see this potentially working in one of two ways there:

* Via [XShape](https://en.wikipedia.org/wiki/Shape_extension), where gtk would send X a mask depending on style of window contents.

    Fairly sure this won't be happening, as styles seem to only affect widgets (and not even their layouts), which are what gtk renders and then pastes into window (which is kinda proxy for graphical server object), in similar fashion as one'd plaster wallpaper onto building's walls - doesn't affect building's shape at all.

    There are separate methods to pass mask for window shape to X11 (or whatever) though - [gtk-widget-shape-combine-region](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-shape-combine-region) or [similar gdk functions](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-shape-combine-region).
    Worst-case, these can be used based on what's in css (gtk can help parsing that) or whatever other config.

* X also can do compositing (compton does that in your case, I guess), when you basically have RGBA "color" for every pixel in that rectangle, where "A" means "alpha" (transparency from opaque 255 to 0) - maybe these "A"s can work from styles?

    I suspect that's exactly what you've tried, and there was still something white poking up from below, which leads to...

* Window has to be filled with transparent "color" (e.g. `cairo_fill()`with `rgba(0,0,0,0)`), so it'd actually have proper transparent bg, not be white underneath all widgets.

Guess I'll look into it when I'll get a chance.
All the relevant stuff should be in display.py file, and `_create_win()` method there, I think.

Don't think I've tried creating gtk3 windows shaped with rgba stuff before, so don't have any particular insight into what happens here already, I'm afraid.

**Comment by mk-fg** [comment]
Hm, apparently it was half what I expected - needed to set window bg transparent (though adding `#notification { background: transparent; }` seemed to be a better way than using gdk/cairo), but other half was `win.set_visual(win.get_screen().get_rgba_visual())`.

Apparently default GdkVisual (struct with stuff like color depth, color byte order, etc) for window wasn't taken from default screen, but something more conservative was used.
Looking at GdkVisual methods and checking its type and such, I can't even see where it hides that "has alpha layer" info, so dunno, guess it's just some weird gtk3 quirk, maybe will go away later.

Seem to work for me now with just `#notification #frame { border-radius: 7px; }` in `~/.config/gtk-3.0/gtk.css`:

![rounded corners popup](http://fraggod.net/static/misc/notification-thing__rounded-corners.jpg)

To test transparency in all its glory, guess you can do something like `* { background: transparent; color: #6ad468; }`.

Thanks for the report!

**Comment by Happy-Ferret** [comment]
Thanks. 

It almost works. 
Unfortunately, I can't seem to get background-color to work now. 

The default  (i. e. freshly cloned from your repository) build doesn't look like in your screenshot but is rather a fully transparent frame. 

Is there perhaps something in your ```~/.config/gtk-3.0 /gtk.css``` that enables this white-ish/creamish background colour?

**Comment by mk-fg** [comment]
Hm, no, it should be [css embedded in the code](https://github.com/mk-fg/notification-thing/blob/master/notification_thing/display.py#L43) doing that.
My base gtk.css is empty, and that one line is enough to add corners, the rest should be all embedded.

I wonder if maybe you have some gtk3 theme affecting the styles?

Here I have this in `~/.config/gtk-3.0/settings.ini`:
```
[Settings]
gtk-icon-theme-name = Tango
gtk-font-name = Luxi Sans 8
gtk-sound-theme-name = site
```

Shouldn't affect styles in my case, but I don't think it'd make sense for a theme to mess that stuff up either, so not sure what might be going on there for you.

* Maybe you have more complex gtk.css, which does that "fully transparent frame" thingie?

    Guess trying empty one should confirm if that's the case.

* Other option I can think of is a [weird fallback system for css that's in display.py](https://github.com/mk-fg/notification-thing/blob/master/notification_thing/display.py#L155).

    Have that because gtk3 css syntax was in a bit of a flux.

    Worst-case, it should fallback to something very basic, and maybe that causes fully-transparent windows with older gtk3?
    Doesn't seem to explain why'd stuff in gtk.css won't work though - it should still override this stuff for any gtk3.

    Should also be easy to check for by looking at stderr produced by the script, i.e. running it from console or something.

**Comment by Happy-Ferret** [comment]
Nope. Empty css here, as well. 

It's not that it won't accept any input from the gtk.css either, btw. It's just that it won't accept any ```background``` tag outside ```#notification``` ```#notification #summary``` and ```#notification #body```.

Changing the ```background```inside ```#notification``` from ```transparent``` to something like ```rgba (0,0,0,0.8);``` obviously brings us back to the previous issue, so that wouldn't work.

**Comment by mk-fg** [comment]
>  It's just that it won't accept any background tag outside `#notification` `#notification #summary` and `#notification #body`.

Um... wait, but these are the only widgets there!
What else would you want to set a background for? Fairly sure it won't work for pango tags.

**Comment by mk-fg** [comment]
Oh, right, there's also `#notification #frame`, did you mean that background doesn't work for that particular one, while works for every other widget?

**Comment by Happy-Ferret** [comment]
If that's the one producing the main background (#d4ded8) , then yes.

**Comment by mk-fg** [comment]
Did you have that "white-ish/creamish background colour" on these popups ever?
I suspect that maybe GtkFrame can't have styles applied to it in your case for some reason...

Reason can still be a theme or an theming engine, I guess, do you have any of these enabled (in "settings.ini" or such)?

**Comment by Happy-Ferret** [comment]
I just remembered I had put some customisations into a theme file residing in /usr/share/themes. 
Perhaps that's what's triggering it. It's quite an old and unstable system that I haven't used since getting my Mac Pro, so I can't even remember all the silliness I committed to it. 

Anyhow. Starting from scratch now, with a fresh system.

**Comment by mk-fg** [comment]
To be fair, I've used the thing on two different distros (exherbo and arch), incl. with oxygen-gtk theme/theming-engine on the former, and have no idea if anyone uses the thing outside of that one-man-userbase, so can't be sure it's not some tweak in my system either (which I might've transferred between distros).

Easy way to test for that would probably be a clean vm, which maybe I'll try eventually.

**Comment by Happy-Ferret** [comment]
That's what I'm basically doing right now. Clean VM based on Ubuntu 15.04.
Running into some weird issue still (dbus-launch is terminated almost immediately upon executing it), but there's hope that this is just some missing dependency or something.

**Comment by Happy-Ferret** [comment]
Ok. It seems it was something inside my themes (I also got some weird css errors that are now gone in the new installation). 

Working perfectly now. Thanks for the assistance :+1:

**Comment by mk-fg** [comment]
Yay! Cheers :+1:
