### ISSUE TITLE
TypeError: could not convert value for property `spacing' from str to gint

### ISSUE THREAD

**Issue by danmilon** [mk-fg/notification-thing#4]
Hey, great notification daemon! Any idea why I get this with an empty configuration file?

```
# create empty configuration file
echo '' > ~/.notification.yaml
# run it
notification-thing --conf ~/.notification.yaml &

# notify-send something
                                      
ERROR:notification_thing.display:Failed to create notification window
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 383, in display
    image, urgency, markup=markup, remote=note.hints.get('x-notification-thing-from-remote') )
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 272, in _create_win
    v_box = Gtk.VBox(spacing=self.layout_margin, expand=False)
  File "/usr/lib/python2.7/site-packages/gi/overrides/__init__.py", line 326, in new_init
    return super_init_func(self, **new_kwargs)
TypeError: could not convert value for property `spacing' from str to gint
```

**Comment by mk-fg** [comment]
Hey, thanks.

I think it should've happened if you've specified --layout-margin as the command-line option - was missing type=int there, and should be fixed in 1f042f8fd.

With --conf it should only happen if you have non-int specified there as well, I think, not with empty one.

Can you check if problem goes away with code from latest git?

**Comment by danmilon** [comment]
Code is from latest git. Wanna check if you get the same odd behavior with an empty configuration? 

On October 31, 2016 7:15:32 PM GMT+02:00, Mike Kazantsev <notifications@github.com> wrote:
>Hey, thanks.
>
>I think it should've happened if you've specified --layout-margin as
>the command-line option - was missing type=int there, and should be
>fixed in 1f042f8fd.
>
>With --conf it should only happen if you have non-int specified there
>as well, I think, not with empty one.
>
>Can you check if problem goes away with code from latest git?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mk-fg/notification-thing/issues/4#issuecomment-257356946

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mk-fg** [comment]
I mean after I wrote that comment.

Yeah, I've tried with empty config and without one, doesn't seem to make any difference - works fine here, and code-wise that "layout_margin" option won't be found/applied from an empty config anyway.

**Comment by mk-fg** [comment]
> > > ... should be fixed in 1f042f8.
> > > Can you check if problem goes away with code from latest git?

> > Code is from latest git.

> I mean after I wrote that comment.

To clarify: I meant that I've pushed two commits since you've opened the issue, which should address it, and was asking to see if they've fixed the problem.

**Comment by danmilon** [comment]
Ah, sorry! I'll test ASAP. 

On November 1, 2016 8:20:56 AM GMT+02:00, Mike Kazantsev <notifications@github.com> wrote:
>> > > ... should be fixed in 1f042f8.
>> > > Can you check if problem goes away with code from latest git?
>
>> > Code is from latest git.
>
>> I mean after I wrote that comment.
>
>To clarify: I meant that I've pushed two commits since you've opened
>the issue, which should address it, and was asking to see if they've
>fixed the problem.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mk-fg/notification-thing/issues/4#issuecomment-257497279

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danmilon** [comment]
Now I get this:
```
╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
╰─$ cat ~/.notification.yaml                                                                          1 ↵
layout:
  anchor: top_right
  margin: 10
╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
╰─$ notification-thing --debug --conf ~/.notification.yaml &                        
[1] 21194
╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
╰─$ DEBUG:daemon:Starting gobject loop
     
╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
╰─$ notify-send test
DEBUG:daemon:Token-pass, 3.00000265439 token(s) left
DEBUG:notification_thing.display:Creating window with parameters: {'body': '', 'markup': 'True', 'summary': 'test', 'urgency': 'normal', 'icon': 'None'}
DEBUG:daemon:Created notification (id: 1, timeout: 5000.0 (ms))
Traceback (most recent call last):                                                                        
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 404, in <lambda>
    win.gobj.connect('configure-event', lambda w,void: self._update_layout())
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 181, in _update_layout
    if 2**ax & self.layout_anchor else self.margins[-2**ax], xrange(2) ))
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 181, in <lambda>
    if 2**ax & self.layout_anchor else self.margins[-2**ax], xrange(2) ))
TypeError: unsupported operand type(s) for &: 'int' and 'str'
```

**Comment by mk-fg** [comment]
Should be fixed in af309d2 (new commit)
Was using action= in cli parser that converted strings to int constants, but bypassed by values in the config.

Guess you can tell that I didn't really bother adjusting these much (defaults are set by/for myself after all) and that you probably are the only other user of the thing ;)

**Comment by danmilon** [comment]
Perfecto! Works like a charm.

I'm happy to be user #2 :)
BTW https://aur.archlinux.org/packages/notification-thing-git

Cheers!

**Comment by mk-fg** [comment]
Nice, I also have rather simplier and more "just for me" pkgbuild, but yours looks much better.
https://github.com/mk-fg/archlinux-pkgbuilds/blob/master/notification-thing-git/PKGBUILD

Thanks for reporting all the things, and hope this weird thing serves you well ;)
