### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'int' and 'str'

### ISSUE THREAD

**Issue by danmilon** [mk-fg/notification-thing#5]
```
╭─ ~ ‹system› 
╰─$ cat ~/.notification.yaml                                                                          1 ↵
layout:
  anchor: top_right
  margin: 25
╭─ ~ ‹system› 
╰─$ notification-thing --debug --conf ~/.notification.yaml --test-message 
DEBUG:notification_thing.display:Creating window with parameters: {'body': 'Desktop notification daemon started successfully on host: <u>delogo</u>\nVersion: <span stretch="extraexpanded">16.10.7</span>\nCode path: <small>/usr/lib/python2.7/site-packages/notification_thing</small>\nSound enabled: <span color="green">true</span>\nPubSub enabled: <span color="red">false</span>', 'markup': 'True', 'summary': 'Notification daemon started <small><tt>\xc2\xaf\\(\xc2\xb0_o)/\xc2\xaf</tt></small>', 'urgency': 'critical', 'icon': 'None'}
DEBUG:daemon:Created notification (id: 1, timeout: 5000.0 (ms))
DEBUG:daemon:Starting gobject loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 404, in <lambda>
    win.gobj.connect('configure-event', lambda w,void: self._update_layout())
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 181, in _update_layout
    if 2**ax & self.layout_anchor else self.margins[-2**ax], xrange(2) ))
  File "/usr/lib/python2.7/site-packages/notification_thing/display.py", line 181, in <lambda>
    if 2**ax & self.layout_anchor else self.margins[-2**ax], xrange(2) ))
TypeError: unsupported operand type(s) for &: 'int' and 'str'
╭─ ~ ‹system› 
╰─$ notification-thing --debug --conf ~/.notification.yaml --test-message --layout-anchor top_right   1 ↵
DEBUG:notification_thing.display:Creating window with parameters: {'body': 'Desktop notification daemon started successfully on host: <u>delogo</u>\nVersion: <span stretch="extraexpanded">16.10.7</span>\nCode path: <small>/usr/lib/python2.7/site-packages/notification_thing</small>\nSound enabled: <span color="green">true</span>\nPubSub enabled: <span color="red">false</span>', 'markup': 'True', 'summary': 'Notification daemon started <small><tt>\xc2\xaf\\(\xc2\xb0_o)/\xc2\xaf</tt></small>', 'urgency': 'critical', 'icon': 'None'}
```

specifying `layout.anchor` in the configuration file fails with the error above. Passing it via the CLI works as expected.

**Comment by mk-fg** [comment]
Hm, looks like duplicate with last comment in #4, and should be fixed in current git, right?
A bit puzzled as to why it seem to be opened after #4 was closed then, maybe some automation magic at work...

**Comment by danmilon** [comment]
Nope, not fixed. Try yourself :)

**Comment by danmilon** [comment]
Sorry, for being sloppy in our conversation. I'm not giving this the required time.
Yeah I was wrong in the other ticket.
Try with latest git, and the configuration as shown in the description of this ticket.

**Comment by mk-fg** [comment]
Hm, weird, seem to be second issue I fail to reproduce:
```
 # fraggod@maled~:-..ication-thing% git ls -1
commit af309d2b5876ee73b938304b357baff92ed55dc9 (HEAD -> master, fg_core/master)
Author: Mike Kazantsev <mk.fraggod@gmail.com>
Date:   Tue Nov 1 20:26:53 2016 +0500

    cli: fix parsing --layout-* enum values

 notification_thing/__init__.py |  2 +-
 notification_thing/daemon.py   | 26 ++++++++++----------------
 2 files changed, 11 insertions(+), 17 deletions(-)

 # fraggod@maled~:-..ication-thing% cat test.yaml
layout:
  anchor: top_right
  margin: 25

 # fraggod@maled~:-..ication-thing% ./notification-thing --debug --conf test.yaml --test-message
DEBUG:notification_thing.display:Creating window with parameters: {'body': 'Desktop notification daemon started successfully on host: <u>malediction</u>\nVersion: <span stretch="extraexpanded">16.11.0</span>\nCode path: <small>/home/fraggod/hatch/notification-thing/notification_thing</small>\nSound enabled: <span color="green">true</span>\nPubSub enabled: <span color="red">false</span>', 'markup': 'True', 'summary': 'Notification daemon started <small><tt>\xc2\xaf\\(\xc2\xb0_o)/\xc2\xaf</tt></small>', 'urgency': 'critical', 'icon': 'None'}
DEBUG:daemon:Created notification (id: 1, timeout: 5000.0 (ms))
DEBUG:daemon:Starting gobject loop
DEBUG:daemon:Closing notification(s) (id: 1, reason: expired)
DEBUG:daemon:Closing notification(s) (id: 1, reason: dismissed)
DEBUG:daemon:NotificationClosed signal (id: 1, reason: expired)
^CTraceback (most recent call last):
  File "./notification-thing", line 782, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./notification-thing", line 779, in main
    loop.run()
  File "/usr/lib/python2.7/site-packages/gi/overrides/GLib.py", line 576, in run
    raise KeyboardInterrupt
KeyboardInterrupt

 # fraggod@maled~:-..ication-thing% ./notification-thing --debug --conf test.yaml --test-message --layout-anchor top_right
DEBUG:notification_thing.display:Creating window with parameters: {'body': 'Desktop notification daemon started successfully on host: <u>malediction</u>\nVersion: <span stretch="extraexpanded">16.11.0</span>\nCode path: <small>/home/fraggod/hatch/notification-thing/notification_thing</small>\nSound enabled: <span color="green">true</span>\nPubSub enabled: <span color="red">false</span>', 'markup': 'True', 'summary': 'Notification daemon started <small><tt>\xc2\xaf\\(\xc2\xb0_o)/\xc2\xaf</tt></small>', 'urgency': 'critical', 'icon': 'None'}
DEBUG:daemon:Created notification (id: 1, timeout: 5000.0 (ms))
DEBUG:daemon:Starting gobject loop
DEBUG:daemon:Closing notification(s) (id: 1, reason: expired)
DEBUG:daemon:Closing notification(s) (id: 1, reason: dismissed)
DEBUG:daemon:NotificationClosed signal (id: 1, reason: expired)
^CTraceback (most recent call last):
  File "./notification-thing", line 782, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./notification-thing", line 779, in main
    loop.run()
  File "/usr/lib/python2.7/site-packages/gi/overrides/GLib.py", line 576, in run
    raise KeyboardInterrupt
KeyboardInterrupt
```

http://fraggod.net/tmp/shot-2016-11-01_22-30-02.jpg
http://fraggod.net/tmp/shot-2016-11-01_22-30-36.jpg

Maybe double-check that you're running latest code, i.e. git pulls stuff in and such (though honestly have no clue why it wouldn't with pkgbuild)...

Just seem to be exact issue that should be fixed (and I was able to reproduce easily) in the latest commit.

**Comment by mk-fg** [comment]
Also, realized that that --test-message does the right thing and prints version (which I put in there for exactly this reason), and yours has `Version: <span stretch="extraexpanded">16.10.7</span>\n` in it, while it should be `Version: <span stretch="extraexpanded">16.11.0</span>\n` (same as mine).

**Comment by mk-fg** [comment]
16.10.7 seem to be from before both fixes in #4, so should have all the problems you've mentioned there.

**Comment by mk-fg** [comment]
One thing that came to mind wrt why you might be running older code in the first comment/snippet is because unlike earlier, you seem to not be in git repo dir, like you were previously, i.e. CWD is ~ here:
```
╭─ ~ ‹system› 
╰─$ notification-thing --debug --conf ~/.notification.yaml --test-message 
```

And `~/Documents/dev/aur/notification-thing-git` in this snippet from #4:
```
╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
╰─$ notify-send test
```

Latter makes `import notification_thing` in python import stuff from current dir, while former will use `/usr/lib/pythonX.Y/site-packages`.

If you run `./notification-thing` or `./notification_thing/daemon.py` directly (i.e. as `__main__` py module), it also has a bit of code to make sure it always runs from checkout, not any site-packages dir, though "cd" into checkout should be enough for that as well.

**Comment by danmilon** [comment]
You're probably right. I'll check again and let you know! Thanks for everything again! 

On November 1, 2016 8:16:39 PM GMT+02:00, Mike Kazantsev <notifications@github.com> wrote:
>One thing that came to mind wrt why you might be running older code in
>the first comment/snippet is because unlike earlier, you seem to not be
>in git repo dir, like you were previously, i.e. CWD is ~ here:
>```
>╭─ ~ ‹system› 
>╰─$ notification-thing --debug --conf ~/.notification.yaml
>--test-message 
>```
>
>And `~/Documents/dev/aur/notification-thing-git` in this snippet from
>#4:
>```
>╭─ ~/Documents/dev/aur/notification-thing-git ‹system› ‹master*› 
>╰─$ notify-send test
>```
>
>Latter makes `import notification_thing` in python import stuff from
>current dir, while former will use `/usr/lib/pythonX.Y/site-packages`.
>
>If you run `./notification-thing` or `./notification_thing/daemon.py`
>directly (i.e. as `__main__` py module), it also has a bit of code to
>make sure it always runs from checkout, not any site-packages dir,
>though "cd" into checkout should be enough for that as well.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mk-fg/notification-thing/issues/5#issuecomment-257647835

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danmilon** [comment]
Indeed, you're right. I now did run the latest version and it works fine. Thanks again :)
