### ISSUE TITLE
ZMQ Json payload

### ISSUE THREAD

**Issue by dev-dsp** [mk-fg/notification-thing#7]
Hi! Are there any specs for that payload?

**Comment by mk-fg** [comment]
It didn't seem to occur to me to make one, but should be trivial to write.

In loose terms, it is this:
```
message: byte(protocol_version) || notification_message_json
notification_message_json: json([hostname, posix_time, notification])
notification: { summary: "", body: "", timeout: -1,
  icon: "", app_name: "generic", replaces_id: 0, actions: [], hints: {}, plain: False }
```

Where "protocol_version" is always 1 (only one supported), and "notification" can have any number of keys mentioned there, with ones that message doesn't have set to default values from above (as defined in core.py Notification class).
Meaning of values in "notification" should be exactly same as in freedesktop.org desktop-notification spec, e.g. "hints" is a mapping that can have "urgency" key with 0 (low), 1 (normal), 2 (critical) values and such. One exception is "plain" flag, which iirc disables parsing pango markup tags in the summary/msg (e.g. fancy bold/color text and such)

So overall message can look something like this, using python bytestring syntax:
`\1["myhost", 1671650325.25, {"summary": "hello", "body": "hello world!"}]`
Actual usage-example: https://github.com/mk-fg/fgtk/blob/8d73dca/desktop/notifications/dovecot-mail#L308-L315

But yeah, should probably write it down in README or a separate file properly, and test to make it sure I didn't miss something.

**Comment by mk-fg** [comment]
Added it under ["Network broadcasting" README section](https://github.com/mk-fg/notification-thing#network-broadcasting) in be40bd2 , fixed a ton of broken links there while at it (gnome stuff changes all their links every couple years). It's pretty much same description as in the comment above though, nothing new.
And again, thanks for mentioning the oversight.
